apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rag-a1732009339035
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-a1732009339035 
  name: rag-a1732009339035
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: rag-a1732009339035 
