apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rag-a1732009339035 
  janus-idp.io/tekton: rag-a1732009339035
  backstage.io/kubernetes-id: rag-a1732009339035
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: rag-a1732009339035
resources: 
- application-dev.yaml